POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFzZHNhIiwiaWQiOiI1YTgwZGEzZmU3MTFiOTA3MjU1OTc1MmQiLCJpYXQiOjE1MTgzOTkwNTV9.rpjQV2tfOWjFu8qibUh21qpEXVNNTITus0BqWdzZegI

{
    "title": "le fuuuuuuuuuuuuuuuuuu",
    "author": "me",
    "url": "asd.fi",
    "likes": 22,
    "userId": "5a80cf01aa337e78693eba9c"
}
