POST http://localhost:3003/api/blogs/5aa3387963fb4722e44743b7/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFzZCIsImlkIjoiNWE4MmZlNzc2YWQ0ZWYzZmM5NTIwYzI3IiwiaWF0IjoxNTE5NDEzODEwfQ.1xk3l4KP9H4U9sp9MIcOHQAB2Kr28Q3kdx4YwKfre98

{
    "comment": "le fuuuuuuuuuuuuuuuuuu"
}
